[package]
name = "data_types"
version = "0.2.0"
edition = "2021"
authors= ["0xSense@github.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
